### ISSUE TITLE
FTBS: latest tvheadend-documentation master 7e10a91

### ISSUE THREAD

**Issue by Corin-EU** [tvheadend/tvheadend-documentation#9]
Latest tvheadend-documentation GIT branch master revision 7e10a91 fails to build from source with same error on both Linux Mint 17.3 (based on Ubuntu 14.04) and Debian Jessie 8.4

{tvheadend-documentation/}# make
make[1]: Entering directory `/srv/repository/git/tvheadend-documentation'
Building build/en/about_project.md
Building build/cs/about_project.md
Building build/en/basic_requirements.md
Building build/cs/basic_requirements.md
Building build/en/before_you_begin.md
Building build/cs/before_you_begin.md
Building build/en/configure_tvheadend.md
Building build/cs/configure_tvheadend.md
Traceback (most recent call last):
  File "./tvhmd.py", line 461, in <module>
    po = f.read(1024*1024)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 805: ordinal not in range(128)
make[1]: *** [build/cs/configure_tvheadend.md] Error 1
make[1]: Leaving directory `/srv/repository/git/tvheadend-documentation'
make: *** [all] Error 2

Above was with default python3.4, trying with python2.7

python2.7 tvhmd.py 
Traceback (most recent call last):
  File "tvhmd.py", line 448, in <module>
    f = open(argv_get('in'))
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by ProfYaffle** [comment]
Thanks for this. The documentation is undergoing a major overhaul at the moment, so I don't know how the current build system plays into that... let me do some digging and find out.
